services:
  db:
    image: postgres:17
    container_name: project-ryka-pomoshi
    restart: always
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: